#!/bin/bash
# Node test scripti - Gazebo olmadan node'lari test eder
# Her terminal icin ayri calistirin

echo "=========================================="
echo "  Node Test Modu"
echo "=========================================="
echo ""
echo "Asagidaki komutlardan birini secin:"
echo ""
echo "1) Patrol Node test:"
echo "   ros2 run patrol_robot patrol_node"
echo ""
echo "2) Zone Monitor test:"
echo "   ros2 run patrol_robot zone_monitor"
echo ""
echo "3) Object Spawner test:"
echo "   ros2 run patrol_robot object_spawner"
echo ""
echo "4) Alert Manager test:"
echo "   ros2 run patrol_robot alert_manager"
echo ""
echo "5) Navigation Controller test:"
echo "   ros2 run patrol_robot navigation_controller"
echo ""
echo "=========================================="
echo "Topic izleme komutlari:"
echo ""
echo "ros2 topic list"
echo "ros2 topic echo /patrol_status"
echo "ros2 topic echo /zone_alert"
echo "ros2 topic echo /system_status"
echo ""
echo "=========================================="
